[package]
name = "Rustaline"
version = "0.1.0"
edition = "2021"


[dependencies]
serenity = { version = "0.12", features = ["client", "gateway", "rustls_backend", "model", "collector"] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }